services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-tracking-server
    ports:
      - "5555:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri sqlite:////data/mlflow.db
      --serve-artifacts
      --artifacts-destination /artifacts
    environment:
      - PYTHONWARNINGS=ignore::DeprecationWarning
    volumes:
      - ./mlflow_db:/data
      - ./mlruns:/artifacts
    restart: unless-stopped
