model:
  best_model: RandomForest
  feature_sets:
    rfe:
    - sqft
    - bedrooms
    - bathrooms
    - location
    - year_built
    - condition
    - house_age
    - price_per_sqft
    - bed_bath_ratio
  mae: 11423.4375
  name: house_price_model
  scoring: r2
  parameters:
    max_depth: null
    n_estimators: 200
  r2_score: 0.9928404561897618
  rmse: 18261.64076520782
  target_variable: price
